name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript type checking
      run: npm run type-check
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: parser-library-coverage
        fail_ci_if_error: false
        
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
      
    - name: Run end-to-end tests
      run: npm run test:e2e
      
    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report-node-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30
        
    - name: Build for production
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-node-${{ matrix.node-version }}
        path: dist/
        retention-days: 7

  # Validate parser configurations
  validate-parsers:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate all parser configurations
      run: node scripts/validate-all-parsers.js
      
    - name: Upload parser validation report
      uses: actions/upload-artifact@v4
      with:
        name: parser-validation-report
        path: |
          parser-validation-report.json
          comprehensive-parser-validation-report.json
        retention-days: 30 